openapi: 3.0.3
info:
  title: To Do API Specification
  description: API documentation for the To Do bounded context.
servers:
  - url: /api/v1
    description: Development Server
tags:
  - name: ToDo
    description: Operations related to the ToDo bounded context.
paths:
  /update-item-description:
    post:
      summary: Update Item Description
      description: Executes the "Update Item Description" command. ...
      operationId: updateItemDescription
      tags:
        - ToDo
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateItemDescriptionRequest'
  /get-item-by-id/{id}:
    get:
      summary: Get Item by ID
      description: Retrieves data based on the "Get Item by ID" query. This is a synchronous query operation.
      operationId: getItemByID
      tags:
        - ToDo
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The unique identifier for the Item.
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          example: An error occurred.
    Item:
      type: object
      description: Represents a Item in the system.
      properties:
        id:
          type: string
          description: Unique identifier for the Item (primary key).
          example: item-001
        description:
          type: string
          description: The description of the Item.
          example: Buy groceries
        isDone:
          type: string
          description: The isDone of the Item.
          example: 'false'
        dueDate:
          type: string
          description: The dueDate of the Item.
          example: '2023-11-15'
        priority:
          type: string
          description: The priority of the Item.
          example: High
      required:
        - id
        - description
        - isDone
        - dueDate
        - priority
    UpdateItemDescriptionRequest:
      type: object
      properties:
        id:
          type: string
          example: item-001
        description:
          type: string
          example: Buy groceries
        isDone:
          type: string
          example: 'false'
      required:
        - id
        - description
        - isDone
  parameters:
    ItemId:
      name: id
      in: path
      required: true
      description: The unique identifier for the Item.
      schema:
        type: string
  responses:
    BadRequest:
      description: 'Bad Request: The server cannot or will not process the request due to something that is perceived to be a client error.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 'Not Found: The server can not find the requested resource.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: 'Internal Server Error: The server has encountered a situation it doesn''t know how to handle.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
